// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Geon":return img`
. . . . . . . . . . . . . 
. . . . . f f f f f f . . 
. . f f f f f f f f f . . 
. f f f f f f f f f f . . 
. f f f f f f f f f f . . 
. f f d f d d f d d f . . 
. f d d f d d f d d f . . 
. f d d d d d d d d f . . 
. f d d d f f f d d f . . 
. f d d d d f d d d f . . 
. f f f f f f f f f f . . 
f f f f f 1 f 1 f f f f . 
f f f f f 1 f 1 f f f f . 
d d f f f 1 f 1 f f d d . 
. . . f f f f f f . . . . 
. . . f f . . f f . . . . 
`;
            case "image2":
            case "Death":return img`
........................
........................
.............fff........
..........ffffff........
.........ffffffff.......
........fffffffff.......
.......ffffffffff.......
.......fffffdffff.......
......ffffddddffff......
......ffddd11dddff......
......fddd1111dddf......
......fbd86dd68dbf......
......fcd891198dcf......
.......fb111111bf.......
.....ffffcdb1bdfff......
.....ffffcbfbfcfff......
.....fffffffffffff......
.....fffffffffffff......
.....ddfffffffffdd......
........fccfffc.........
..........ccccc.........
........................
........................
........................
`;
            case "image3":
            case "0":return img`
..............................
..............................
..............................
..............................
............fffffff...........
.........fffffffffff..........
.........fffffffffff..........
........fffffffffffffff.......
.....fffffffffffffffffffff....
.....fffffffffffffffffffff....
.....fffffeeeeeeeeeeffffff....
......fffeeeeeeeeeeeefff......
.......ffeeeeeeeeeeeeff.......
.......ffddddddddddddff.......
.......fffddddddddddfff.......
........fffddddddddff.........
..........fdffffffdf..........
..........ffffdddfff..........
...........fffffffff..........
...........ffffffff...........
..........ffffffffff..........
.......ffffffdddddffffff......
....ffffffffffdddffffffff.....
...fffffffffffffffffffffff....
..fffffffffffffffffffffffff...
.fffffffffffffffffffffffffff..
.ffffffffffffffffffffffffffff.
.ffffffffffffffffffffffffffff.
.ffffffffffff1fff1fffffffffff.
.ffffffffffff1fff1fffffffffff.
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "song1":
            case "Melody1":return hex`0078000408020100001c00010a006400f4016400000400000000000000000000000000050000043c0000000400012008000c0001190c001000011910001400011918001c00012020002400011e24002800011d28002c00011e30003400012038003c000119`;
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
